#!/bin/bash

/usr/bin/dos2unix -q ${BASH_ARGV[0]}

#$ -cwd 
#$ -P bf528 
#$ -j y 
#$ -pe mpi_16_tasks_per_node 16
 
s1='SRR3879604'
s2='SRR3879605'
s3='SRR3879606'

path="/projectnb/bf528/project_4_scrnaseq/fastq/" 

path1=${path}${s1}/${s1}_1_bc.fastq.gz
path2=${path}${s2}/${s2}_1_bc.fastq.gz
path3=${path}${s3}/${s3}_1_bc.fastq.gz

gzip -d -c $path1 | awk '$1 ~ /^@/{{gsub(/.*=/, "", $2)gsub(/.*=/, "", $3);bc=$2$3}{print ($1, bc, $4)}}' > results/out_$s1.csv

gzip -d -c $path2 | awk '$1 ~ /^@/{{gsub(/.*=/, "", $2)gsub(/.*=/, "", $3);bc=$2$3}{print ($1, bc, $4)}}' > results/out_$s2.csv

gzip -d -c $path3 | awk '$1 ~ /^@/{{gsub(/.*=/, "", $2)gsub(/.*=/, "", $3);bc=$2$3}{print($1, bc, $4)}}' > results/out_$s3.csv
