#!/bin/bash

/usr/bin/dos2unix -q ${BASH_ARGV[0]}

#$ -cwd 
#$ -P bf528 
#$ -j y 
#$ -pe mpi_16_tasks_per_node 16
 
module load salmon

grep "^>" <(gunzip -c GRCh38.p13.genome.fa.gz) | cut -d " " -f 1 > decoys.txt
sed -i.bak -e 's/>//g' decoys.txt

cat gencode.v37.transcripts.fa.gz GRCh38.p13.genome.fa.gz > gentrome.fa.gz

salmon index -t gentrome.fa.gz -d decoys.txt -p 12 -i salmon_index --gencode
